# Notebook guide

This notebook explores and compares diversification-oriented ETF selection methods.

## Inputs
- data/raw/volume_screen.csv
- data/raw/daily_close_volume_screened_2016_2025.parquet

## What to verify
- Universe filter impact and survivor counts
- Diversity diagnostics (distance/correlation structure)
- Stability and overlap across selection methods

Execute cells in order so all matrices and plots share the same filtered universe.

# Explore Correlation Selection Methods

This notebook focuses on the selection methods compared interactively here. Shared data preparation happens once, then each included method gets a Markdown explanation and a dedicated execution cell.

Every selector below treats `VOO` and `VEA` as hard portfolio anchors. Those two ETFs are always included first, and each method only decides how to fill the remaining slots with low-correlation names.

The notebook also applies the correlation-stage eligibility screens before any method runs: first `start_date <= 2018-01-01`, then a cumulative log-return hurdle over the full 2018-01-01 to 2025-12-31 window. The shared setup cell includes `RETURN_FREQUENCY`, so you can switch between daily and weekly log returns without changing any method cell.

In [19]:
from __future__ import annotations
from pathlib import Path
import importlib
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display

PROJECT_ROOT = Path.cwd().resolve()
if not (PROJECT_ROOT / "GUIDE_ROOT.md").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
for _candidate in [PROJECT_ROOT / "src", PROJECT_ROOT]:
    if str(_candidate) not in sys.path:
        sys.path.insert(0, str(_candidate))

import notebook_support as nb_support
import correlation_analysis.correlate_greedy as correlate_greedy
import correlation_analysis.correlate_kmedoids as correlate_kmedoids
import correlation_analysis.correlate_maxdiv as correlate_maxdiv
import correlation_analysis.correlate_utils as utils

nb_support = importlib.reload(nb_support)
correlate_greedy = importlib.reload(correlate_greedy)
correlate_kmedoids = importlib.reload(correlate_kmedoids)
correlate_maxdiv = importlib.reload(correlate_maxdiv)
utils = importlib.reload(utils)

from data_pipeline.paths import PRICE_PARQUET, SCREEN_CSV

bootstrap_notebook = nb_support.bootstrap_notebook
build_membership_frame = nb_support.build_membership_frame
build_overlap_matrix = nb_support.build_overlap_matrix
ensure_required_artifacts = nb_support.ensure_required_artifacts
load_local_price_data = nb_support.load_local_price_data

PROJECT_ROOT = bootstrap_notebook(PROJECT_ROOT)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 180)

TOP_N = 30
ANALYSIS_START = "20210101"
ANALYSIS_END = "20251231"
RETURN_FREQUENCY = "weekly"
MIN_TOTAL_RETURN_HURDLE = 0.1
MIN_AVERAGE_YEARLY_RETURN = 0.0
MIN_ANN_VOL = 0.1
MAX_ANN_VOL = 0.60
BLACKLIST_TICKERS = [
    "GLD",
    "ASHR",
    "ELV",
    "KSA",
    "EWZ",
    "UGL",
    "VNM",
    "ECH",
    "BAR",
    "SGOL",
    "PHYS",
    "OUNZ",
    "GDXJ",
    "IAU",
    "INDA",
    "EPI",
    "GLODM",
    "TBT",
]
# Required core holdings seeded before any method optimises
ANCHOR_TICKERS = ["VOO", "VEA", "VWO"]
ANALYSIS_START, ANALYSIS_END = utils.resolve_analysis_window(
    ANALYSIS_START,
    ANALYSIS_END,
)

ensure_required_artifacts(
    {
        "volume screen": SCREEN_CSV,
        "daily parquet": PRICE_PARQUET,
    }
)

screened_candidates = utils.load_screened_universe()
candidates = utils.apply_start_date_filter(
    screened_candidates,
    start_date=ANALYSIS_START,
)
prices_long = load_local_price_data(["ticker", "date", "close_price"]).rename(
    columns={"ticker": "symbol"}
)
prices_long = prices_long[prices_long["symbol"].isin(candidates["ticker"])].copy()
prices_long["date"] = pd.to_datetime(prices_long["date"])
prices_long = prices_long[
    (prices_long["date"] >= pd.Timestamp(ANALYSIS_START))
    & (prices_long["date"] <= pd.Timestamp(ANALYSIS_END))
].copy()
log_ret, survivors = utils.build_return_matrix(
    prices_long,
    candidates,
    return_frequency=RETURN_FREQUENCY,
)

coverage_candidate_count = len(candidates)
coverage_survivor_count = len(survivors)
preselection_audit_rows: list[dict[str, object]] = []


def subset_survivors_to_tickers(
    filtered_log_ret: pd.DataFrame,
    filtered_survivors: pd.DataFrame,
    passing_tickers: list[str],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    selected_log_ret = filtered_log_ret.loc[:, passing_tickers].copy()
    selected_survivors = filtered_survivors[
        filtered_survivors["ticker"].isin(passing_tickers)
    ].copy()
    selected_survivors = selected_survivors.sort_values(
        "vol_combined",
        ascending=False,
    ).reset_index(drop=True)
    return selected_log_ret, selected_survivors


def record_audit_step(
    step_name: str,
    threshold: str,
    count_before: int,
    count_after: int,
) -> None:
    preselection_audit_rows.append(
        {
            "step": step_name,
            "threshold": threshold,
            "count_before": count_before,
            "count_after": count_after,
            "removed_count": count_before - count_after,
        }
    )


record_audit_step(
    step_name="coverage",
    threshold=f">= {utils.MIN_COVERAGE:.0%} observed return rows",
    count_before=coverage_candidate_count,
    count_after=coverage_survivor_count,
)

current_log_ret = log_ret
current_survivors = survivors

count_before = len(current_survivors)
current_log_ret, current_survivors = utils.filter_blacklisted_tickers(
    current_log_ret,
    current_survivors,
    blacklist_tickers=BLACKLIST_TICKERS,
    anchor_tickers=ANCHOR_TICKERS,
)
record_audit_step(
    step_name="blacklist",
    threshold=", ".join(BLACKLIST_TICKERS),
    count_before=count_before,
    count_after=len(current_survivors),
)

count_before = len(current_survivors)
current_log_ret, current_survivors = utils.filter_min_total_return(
    current_log_ret,
    current_survivors,
    min_total_return=MIN_TOTAL_RETURN_HURDLE,
    start_date=ANALYSIS_START,
    end_date=ANALYSIS_END,
    anchor_tickers=ANCHOR_TICKERS,
)
record_audit_step(
    step_name="min_total_return",
    threshold=f">= {MIN_TOTAL_RETURN_HURDLE:.4f} cumulative log return",
    count_before=count_before,
    count_after=len(current_survivors),
)

count_before = len(current_survivors)
current_log_ret, current_survivors = utils.filter_min_average_yearly_return(
    current_log_ret,
    current_survivors,
    min_average_yearly_return=MIN_AVERAGE_YEARLY_RETURN,
    anchor_tickers=ANCHOR_TICKERS,
)
record_audit_step(
    step_name="min_average_yearly_return",
    threshold=f">= {MIN_AVERAGE_YEARLY_RETURN:.4f} average calendar-year log return",
    count_before=count_before,
    count_after=len(current_survivors),
)

ann_vols = utils.compute_annualized_volatility(
    current_log_ret,
    return_frequency=RETURN_FREQUENCY,
)
dropped_min_vol = ann_vols[
    (ann_vols < MIN_ANN_VOL) & (~ann_vols.index.isin(ANCHOR_TICKERS))
].sort_values()
passing_min_vol = [
    ticker for ticker in current_log_ret.columns if ticker not in dropped_min_vol.index
]
count_before = len(current_survivors)
current_log_ret, current_survivors = subset_survivors_to_tickers(
    current_log_ret,
    current_survivors,
    passing_min_vol,
)
utils.ensure_anchor_tickers(
    current_log_ret.columns.tolist(),
    "minimum-volatility-filtered survivor universe",
    ANCHOR_TICKERS,
)
record_audit_step(
    step_name="min_ann_vol",
    threshold=f">= {MIN_ANN_VOL:.1%}",
    count_before=count_before,
    count_after=len(current_survivors),
)

ann_vols = utils.compute_annualized_volatility(
    current_log_ret,
    return_frequency=RETURN_FREQUENCY,
)
dropped_max_vol = ann_vols[
    (ann_vols > MAX_ANN_VOL) & (~ann_vols.index.isin(ANCHOR_TICKERS))
].sort_values(ascending=False)
passing_max_vol = [
    ticker for ticker in current_log_ret.columns if ticker not in dropped_max_vol.index
]
count_before = len(current_survivors)
current_log_ret, current_survivors = subset_survivors_to_tickers(
    current_log_ret,
    current_survivors,
    passing_max_vol,
)
utils.ensure_anchor_tickers(
    current_log_ret.columns.tolist(),
    "maximum-volatility-filtered survivor universe",
    ANCHOR_TICKERS,
)
record_audit_step(
    step_name="max_ann_vol",
    threshold=f"<= {MAX_ANN_VOL:.0%}",
    count_before=count_before,
    count_after=len(current_survivors),
)

log_ret = current_log_ret
survivors = current_survivors
corr = utils.compute_spearman_corr(log_ret)
dist = utils.compute_distance_matrix(corr)
preselection_audit = pd.DataFrame(preselection_audit_rows)
panel_summary = pd.Series(
    {
        "top_n_per_method": TOP_N,
        "return_frequency": RETURN_FREQUENCY,
        "required_anchors": ", ".join(ANCHOR_TICKERS),
        "manual_blacklist": ", ".join(BLACKLIST_TICKERS),
        "analysis_start": ANALYSIS_START,
        "analysis_end": ANALYSIS_END,
        "history_start_cutoff": ANALYSIS_START,
        "history_end": ANALYSIS_END,
        "min_total_return_hurdle": f"{MIN_TOTAL_RETURN_HURDLE:.4f} cumulative log return",
        "min_average_yearly_return": f"{MIN_AVERAGE_YEARLY_RETURN:.4f} average calendar-year log return",
        "min_ann_vol": f"{MIN_ANN_VOL:.1%}",
        "max_ann_vol": f"{MAX_ANN_VOL:.0%}",
        "candidate_count_after_liquidity_screen": len(screened_candidates),
        "candidate_count_after_start_date_filter": len(candidates),
        "survivor_count_after_coverage_filter": coverage_survivor_count,
        "survivor_count_after_all_preselection_filters": len(survivors),
        "return_observations": len(log_ret),
        "start_date": str(log_ret.index.min().date()),
        "end_date": str(log_ret.index.max().date()),
    },
    name="value",
)
print("Shared return/correlation panel:")
display(panel_summary.to_frame())
print("Pre-selection audit:")
display(preselection_audit)

selection_results: dict[str, dict[str, object]] = {}


def plot_selected_corr(selected: list[str], title: str) -> None:
    selected_corr = corr.loc[selected, selected]
    fig, ax = plt.subplots(figsize=(8, 6), constrained_layout=True)
    image = ax.imshow(selected_corr.values, cmap="coolwarm", vmin=-1.0, vmax=1.0)
    ax.set_xticks(range(len(selected)), selected, rotation=35)
    ax.set_yticks(range(len(selected)), selected)
    ax.set_title(title)
    fig.colorbar(image, ax=ax, fraction=0.046)
    display(fig)
    plt.close(fig)


def summarize_selection(method_name: str, selected: list[str]) -> pd.DataFrame:
    top_selected = utils.build_anchor_first_selection(
        ranked_tickers=selected,
        available_tickers=selected,
        n_select=TOP_N,
        anchor_tickers=ANCHOR_TICKERS,
    )
    stats = utils.compute_stats(
        top_selected,
        log_ret,
        survivors,
        return_frequency=RETURN_FREQUENCY,
        anchor_tickers=ANCHOR_TICKERS,
    ).reset_index(drop=True)
    selection_results[method_name] = {"selected": top_selected, "stats": stats}
    print(f"{method_name} top-{TOP_N} tickers: {', '.join(top_selected)}")
    display(
        stats[
            [
                "ticker",
                "is_anchor",
                "ann_return",
                "ann_vol",
                "sharpe",
                "max_drawdown",
                "avg_abs_corr",
            ]
        ].round(4)
    )
    plot_selected_corr(top_selected, f"{method_name} selected-correlation heatmap")
    return stats

Candidates after start_date filter (<= 2021-01-01): 425 / 500 (dropped 75)
Resampled daily closes to weekly closes using W-FRI.
Price matrix shape before coverage filter: (261, 425) (261 weekly periods)
Coverage filter dropped 4 symbols (< 80% of trading days): ['AMJ', 'BSCO', 'EU', 'RTL']
Weekly log-return matrix shape: (260, 421)
Manual blacklist dropped 17 symbols before the statistical filters: ['ASHR', 'BAR', 'ECH', 'ELV', 'EPI', 'EWZ', 'GDXJ', 'GLD', 'IAU', 'INDA', 'KSA', 'OUNZ', 'PHYS', 'SGOL', 'TBT', 'UGL', 'VNM']
Total-return hurdle dropped 123 symbols below 0.1000 log total return (2021-01-01 to 2025-12-31).
Top 15 dropped: ['UVXY', 'SOXS', 'FNGD', 'BOIL', 'TECS', 'VIXY', 'VXX', 'JDST', 'DUST', 'ZSL', 'DRIP', 'SQQQ', 'LABU', 'KOLD', 'FAZ']
Computing Spearman correlation matrix ...
Correlation matrix shape: (227, 227)
Shared return/correlation panel:

                                                                                           value
top_n_per_method                                                                              30
return_frequency                                                                          weekly
required_anchors                                                                   VOO, VEA, VWO
manual_blacklist                               GLD, ASHR, ELV, KSA, EWZ, UGL, VNM, ECH, BAR, ...
analysis_start                                                                        2021-01-01
analysis_end                                                                          2025-12-31
history_start_cutoff                                                                  2021-01-01
history_end                                                                           2025-12-31
min_total_return_hurdle                                             0.1000 cumulative log return
min_average_yearly_return                                0.0000 average calendar-year log return
min_ann_vol                                                                                10.0%
max_ann_vol                                                                                  60%
candidate_count_after_liquidity_screen                                                       500
candidate_count_after_start_date_filter                                                      425
survivor_count_after_coverage_filter                                                         421
survivor_count_after_all_preselection_filters                                                227
return_observations                                                                          260
start_date                                                                            2021-01-15
end_date                                                                              2026-01-02

Pre-selection audit:

                        step                                          threshold  count_before  count_after  removed_count
0                   coverage                        >= 80% observed return rows           425          421              4
1                  blacklist  GLD, ASHR, ELV, KSA, EWZ, UGL, VNM, ECH, BAR, ...           421          404             17
2           min_total_return                    >= 0.1000 cumulative log return           404          281            123
3  min_average_yearly_return         >= 0.0000 average calendar-year log return           281          281              0
4                min_ann_vol                                           >= 10.0%           281          239             42
5                max_ann_vol                                             <= 60%           239          227             12

## Greedy Maximin

`select_by_greedy()` from `correlate_greedy.py` is seeded with the required anchors `VOO` and `VEA`. After those two names are locked in, each new ETF maximizes its minimum distance to the already selected set.

The greedy step is still:

$$
\operatorname*{argmax}_{c \notin S} \; \min_{s \in S} D(c, s)
$$

That makes it a direct low-correlation expansion around the hard anchor pair rather than around the most-liquid ETF.

In [20]:
greedy_selected, greedy_marginal = correlate_greedy.select_by_greedy(
    dist, survivors, n_select=TOP_N, anchor_tickers=ANCHOR_TICKERS
)
greedy_stats = summarize_selection("greedy", greedy_selected)

fig, ax = plt.subplots(figsize=(10, 4), constrained_layout=True)
ax.plot(
    range(2, len(greedy_marginal) + 1),
    greedy_marginal[1:],
    marker="o",
    linewidth=1.8,
    color="#1f77b4",
)
ax.set_title("Greedy marginal diversity")
ax.set_xlabel("Selection step")
ax.set_ylabel("Minimum distance to current set")
ax.grid(alpha=0.3)
display(fig)
plt.close(fig)

Greedy Maximin: fixed anchors = VOO, VEA, VWO
Selecting 30 ETFs ...
  Step  4: added TMV       (marginal min-dist = 0.7329)
  Step  5: added BNO       (marginal min-dist = 0.6197)
  Step  6: added DBA       (marginal min-dist = 0.6171)
  Step  7: added GLDM      (marginal min-dist = 0.5897)
  Step  8: added XLU       (marginal min-dist = 0.5412)
  Step  9: added URNM      (marginal min-dist = 0.5346)
  Step 10: added KRE       (marginal min-dist = 0.4825)
  Step 11: added AMLP      (marginal min-dist = 0.4790)
  Step 12: added BIZD      (marginal min-dist = 0.4649)
  Step 13: added HDV       (marginal min-dist = 0.4614)
  Step 14: added XLV       (marginal min-dist = 0.4489)
  Step 15: added DXJ       (marginal min-dist = 0.4471)
  Step 16: added ILF       (marginal min-dist = 0.4399)
  Step 17: added XME       (marginal min-dist = 0.4349)
  Step 18: added XLRE      (marginal min-dist = 0.4323)
  Step 19: added KIE       (marginal min-dist = 0.4226)
  Step 20: added JETS      (marginal min-dist = 0.4221)
  Step 21: added ITB       (marginal min-dist = 0.4179)
  Step 22: added DFEN      (marginal min-dist = 0.4169)
  Step 23: added XLP       (marginal min-dist = 0.4155)
  Step 24: added EWS       (marginal min-dist = 0.4092)
  Step 25: added REM       (marginal min-dist = 0.4087)
  Step 26: added XRT       (marginal min-dist = 0.3936)
  Step 27: added OIH       (marginal min-dist = 0.3935)
  Step 28: added EWW       (marginal min-dist = 0.3904)
  Step 29: added IYZ       (marginal min-dist = 0.3883)
  Step 30: added IGF       (marginal min-dist = 0.3878)
greedy top-30 tickers: VOO, VEA, VWO, TMV, BNO, DBA, GLDM, XLU, URNM, KRE, AMLP, BIZD, HDV, XLV, DXJ, ILF, XME, XLRE, KIE, JETS, ITB, DFEN, XLP, EWS, REM, XRT, OIH, EWW, IYZ, IGF

   ticker  is_anchor  ann_return  ann_vol  sharpe  max_drawdown  avg_abs_corr
0     DXJ          0      0.2153   0.1842  0.8976        0.1663        0.3496
1    GLDM          0      0.1683   0.1512  0.7819        0.1731        0.1884
2    AMLP          0      0.1949   0.2175  0.6661        0.1693        0.3328
3     XME          0      0.2178   0.3342  0.5022        0.3621        0.4623
4     VOO          1      0.1303   0.1609  0.4988        0.2393        0.5032
5    DFEN          0      0.3330   0.5935  0.4768        0.5464        0.4654
6     KIE          0      0.1291   0.1806  0.4380        0.1482        0.4340
7     DBA          0      0.1166   0.1536  0.4338        0.1486        0.1668
8     HDV          0      0.0984   0.1274  0.3799        0.1535        0.4553
9     TMV          0      0.1993   0.4376  0.3411        0.4669        0.1319
10   URNM          0      0.1985   0.4639  0.3202        0.4815        0.3157
11   BIZD          0      0.1033   0.1680  0.3169        0.2152        0.3986
12    IGF          0      0.0937   0.1469  0.2972        0.1972        0.4958
13    EWW          0      0.1156   0.2234  0.2937        0.3076        0.4127
14    BNO          0      0.1412   0.3236  0.2818        0.3176        0.1910
15    ITB          0      0.1202   0.2831  0.2480        0.4071        0.3881
16    XLU          0      0.0920   0.1697  0.2474        0.2357        0.3438
17    EWS          0      0.0875   0.1770  0.2121        0.2788        0.4072
18    VEA          1      0.0786   0.1647  0.1737        0.2950        0.5096
19    OIH          0      0.1121   0.4075  0.1524        0.3994        0.3581
20    XLV          0      0.0703   0.1471  0.1381        0.1627        0.3554
21    ILF          0      0.0715   0.2359  0.0913        0.2785        0.3874
22    XLP          0      0.0562   0.1266  0.0492        0.1467        0.3661
23    XRT          0      0.0605   0.2691  0.0389        0.4382        0.4339
24   XLRE          0      0.0570   0.1892  0.0370        0.3371        0.4262
25    KRE          0      0.0516   0.2960  0.0053        0.5253        0.4253
26   JETS          0      0.0499   0.2991 -0.0004        0.4726        0.3795
27    IYZ          0      0.0418   0.1849 -0.0445        0.3952        0.4444
28    VWO          1      0.0412   0.1652 -0.0532        0.3388        0.4212
29    REM          0      0.0246   0.2483 -0.1023        0.4130        0.4739

## Anchored K-Medoids

`select_by_kmedoids()` from `correlate_kmedoids.py` treats `VOO` and `VEA` as fixed medoids, then optimizes the remaining medoids on the same signed-distance matrix.

The objective is medoid-based cluster compression on the signed-distance geometry, so each selected ETF is an actual tradable representative rather than a synthetic centroid.

In [21]:
kmedoids_selected, kmedoids_info = correlate_kmedoids.select_by_kmedoids(
    dist, survivors, n_select=TOP_N, anchor_tickers=ANCHOR_TICKERS
)
kmedoids_stats = summarize_selection("kmedoids", kmedoids_selected)

print("Anchored k-medoids cluster summary:")
display(kmedoids_info.round(4))

fig, ax = plt.subplots(figsize=(10, 4), constrained_layout=True)
ax.bar(kmedoids_info["ticker"], kmedoids_info["cluster_size"], color="#2f4b7c")
ax.set_title("Anchored k-medoids cluster sizes")
ax.set_ylabel("Assigned ETF count")
ax.tick_params(axis="x", rotation=35)
ax.grid(axis="y", alpha=0.3)
display(fig)
plt.close(fig)

  k-medoids iteration  1: updated medoids
  k-medoids iteration  2: updated medoids
  k-medoids iteration  3: updated medoids
  k-medoids iteration  4: converged
Anchored k-medoids selected 30 ETFs.
Fixed anchors: VOO, VEA, VWO
kmedoids top-30 tickers: VOO, VEA, VWO, VONV, MDY, VDE, UCO, SLV, XLF, IYR, GUNR, TMV, ITB, URA, XLP, XLV, AMLP, BIZD, DBA, DFEN, DXJ, EWS, EWW, IGF, ILF, IYZ, JETS, REM, XLU, XRT

   ticker  is_anchor  ann_return  ann_vol  sharpe  max_drawdown  avg_abs_corr
0     DXJ          0      0.2153   0.1842  0.8976        0.1663        0.3707
1    AMLP          0      0.1949   0.2175  0.6661        0.1693        0.3451
2     SLV          0      0.2026   0.2936  0.5197        0.3585        0.2292
3     VOO          1      0.1303   0.1609  0.4988        0.2393        0.5348
4     VDE          0      0.1946   0.2915  0.4959        0.2271        0.3497
5    DFEN          0      0.3330   0.5935  0.4768        0.5464        0.4821
6     DBA          0      0.1166   0.1536  0.4338        0.1486        0.1839
7     URA          0      0.2302   0.4157  0.4336        0.3709        0.3725
8     XLF          0      0.1308   0.1935  0.4175        0.2510        0.5260
9     TMV          0      0.1993   0.4376  0.3411        0.4669        0.1299
10   VONV          0      0.0995   0.1492  0.3320        0.1845        0.6012
11   BIZD          0      0.1033   0.1680  0.3169        0.2152        0.4135
12    IGF          0      0.0937   0.1469  0.2972        0.1972        0.5145
13    EWW          0      0.1156   0.2234  0.2937        0.3076        0.4313
14    ITB          0      0.1202   0.2831  0.2480        0.4071        0.4054
15    XLU          0      0.0920   0.1697  0.2474        0.2357        0.3485
16    EWS          0      0.0875   0.1770  0.2121        0.2788        0.4240
17   GUNR          0      0.0905   0.1940  0.2089        0.2255        0.5066
18    VEA          1      0.0786   0.1647  0.1737        0.2950        0.5367
19    MDY          0      0.0762   0.1870  0.1399        0.2290        0.5758
20    XLV          0      0.0703   0.1471  0.1381        0.1627        0.3698
21    UCO          0      0.1277   0.5712  0.1360        0.6442        0.2277
22    ILF          0      0.0715   0.2359  0.0913        0.2785        0.4086
23    XLP          0      0.0562   0.1266  0.0492        0.1467        0.3667
24    XRT          0      0.0605   0.2691  0.0389        0.4382        0.4569
25    IYR          0      0.0501   0.1850  0.0008        0.3344        0.4723
26   JETS          0      0.0499   0.2991 -0.0004        0.4726        0.3952
27    IYZ          0      0.0418   0.1849 -0.0445        0.3952        0.4575
28    VWO          1      0.0412   0.1652 -0.0532        0.3388        0.4496
29    REM          0      0.0246   0.2483 -0.1023        0.4130        0.4924

Anchored k-medoids cluster summary:

   ticker  cluster_size  avg_cluster_distance  is_anchor_medoid  selection_rank
0     VOO            47                0.1788                 1               1
1     VEA            42                0.2512                 1               2
2     VWO            13                0.2017                 1               3
3    VONV            34                0.2115                 0               4
4     MDY            24                0.1865                 0               5
5     VDE            10                0.1244                 0               6
6     UCO             9                0.1860                 0               7
7     SLV             9                0.2302                 0               8
8     XLF             7                0.1957                 0               9
9     IYR             5                0.1017                 0              10
10   GUNR             3                0.2204                 0              11
11    TMV             2                0.0608                 0              12
12    ITB             2                0.0778                 0              13
13    URA             2                0.0851                 0              14
14    XLP             2                0.1552                 0              15
15    XLV             2                0.1916                 0              16
16   AMLP             1                0.0000                 0              17
17   BIZD             1                0.0000                 0              18
18    DBA             1                0.0000                 0              19
19   DFEN             1                0.0000                 0              20
20    DXJ             1                0.0000                 0              21
21    EWS             1                0.0000                 0              22
22    EWW             1                0.0000                 0              23
23    IGF             1                0.0000                 0              24
24    ILF             1                0.0000                 0              25
25    IYZ             1                0.0000                 0              26
26   JETS             1                0.0000                 0              27
27    REM             1                0.0000                 0              28
28    XLU             1                0.0000                 0              29
29    XRT             1                0.0000                 0              30

## Maximum Diversification Ratio

`select_by_maxdiv()` from `correlate_maxdiv.py` greedily adds the ETF that maximises the equal-weight **diversification ratio** of the growing basket:

$
DR = \frac{\bar{\sigma}}{\sigma_p^{EW}} = \frac{\frac{1}{N}\sum_i \sigma_i}{\sqrt{\mathbf{w}^T \Sigma \mathbf{w}}}
$

Unlike the other methods, this directly optimises a portfolio-level diversification metric using the **full covariance structure** rather than pairwise distances or cluster membership. DR = 1 means perfect correlation (no benefit); higher is better.

Reference: Choueifaty & Coignard (2008), "Toward Maximum Diversification."

In [22]:
maxdiv_selected, maxdiv_marginal_drs = correlate_maxdiv.select_by_maxdiv(
    log_ret, survivors, n_select=TOP_N, anchor_tickers=ANCHOR_TICKERS
)
maxdiv_stats = summarize_selection("maxdiv", maxdiv_selected)

fig, ax = plt.subplots(figsize=(10, 4), constrained_layout=True)
# Skip first entry (NaN for single-asset basket)
steps = list(range(2, len(maxdiv_marginal_drs) + 1))
dr_values = maxdiv_marginal_drs[1:]
ax.plot(steps, dr_values, marker="o", linewidth=1.8, color="#2f4b7c")
ax.set_title("Max-DR: diversification ratio vs basket size")
ax.set_xlabel("Number of ETFs in basket")
ax.set_ylabel("Diversification Ratio (higher = better)")
ax.grid(alpha=0.3)
display(fig)
plt.close(fig)

  Anchors seeded: VOO, VEA, VWO
  Step   4: TMV     DR = 1.5488
  Step   5: GLDM    DR = 1.7040
  Step   6: ITB     DR = 1.8142
  Step   7: FTGC    DR = 1.9221
  Step   8: XLU     DR = 1.9637
  Step   9: TBF     DR = 2.0077
  Step  10: DBA     DR = 2.0388
  Step  15: EWT     DR = 2.0622
  Step  20: USO     DR = 2.0086
  Step  25: XRT     DR = 1.9525
  Step  30: COMT    DR = 1.9061
Max-DR selected 30 ETFs.
maxdiv top-30 tickers: VOO, VEA, VWO, TMV, GLDM, ITB, FTGC, XLU, TBF, DBA, AAAU, XLP, XLV, BNO, EWT, CEF, JETS, SPLV, EFAV, USO, SCHH, EWS, PSLV, DXJ, XRT, DBO, EEMV, KIE, URNM, COMT

   ticker  is_anchor  ann_return  ann_vol  sharpe  max_drawdown  avg_abs_corr
0     DXJ          0      0.2153   0.1842  0.8976        0.1663        0.2816
1    AAAU          0      0.1705   0.1484  0.8116        0.1700        0.2798
2    GLDM          0      0.1683   0.1512  0.7819        0.1731        0.2726
3     CEF          0      0.1754   0.2050  0.6116        0.2447        0.2735
4    PSLV          0      0.1967   0.2860  0.5130        0.3693        0.2885
5     VOO          1      0.1303   0.1609  0.4988        0.2393        0.4203
6     KIE          0      0.1291   0.1806  0.4380        0.1482        0.3188
7     DBA          0      0.1166   0.1536  0.4338        0.1486        0.1786
8     EWT          0      0.1407   0.2222  0.4079        0.3831        0.3158
9     TBF          0      0.1052   0.1461  0.3780        0.1637        0.1863
10   FTGC          0      0.1414   0.2488  0.3673        0.3408        0.3012
11    TMV          0      0.1993   0.4376  0.3411        0.4669        0.1911
12   URNM          0      0.1985   0.4639  0.3202        0.4815        0.2717
13   COMT          0      0.1165   0.2109  0.3151        0.2699        0.2780
14    BNO          0      0.1412   0.3236  0.2818        0.3176        0.2322
15    USO          0      0.1331   0.3224  0.2577        0.3468        0.2410
16    ITB          0      0.1202   0.2831  0.2480        0.4071        0.3034
17    XLU          0      0.0920   0.1697  0.2474        0.2357        0.2914
18    EWS          0      0.0875   0.1770  0.2121        0.2788        0.3552
19    VEA          1      0.0786   0.1647  0.1737        0.2950        0.4382
20    XLV          0      0.0703   0.1471  0.1381        0.1627        0.3123
21   SPLV          0      0.0654   0.1274  0.1206        0.1598        0.3491
22    DBO          0      0.0837   0.2931  0.1151        0.3612        0.2412
23   EFAV          0      0.0573   0.1210  0.0601        0.2692        0.4159
24    XLP          0      0.0562   0.1266  0.0492        0.1467        0.3029
25    XRT          0      0.0605   0.2691  0.0389        0.4382        0.3381
26   SCHH          0      0.0514   0.1883  0.0074        0.3348        0.3736
27   JETS          0      0.0499   0.2991 -0.0004        0.4726        0.2726
28    VWO          1      0.0412   0.1652 -0.0532        0.3388        0.3978
29   EEMV          0      0.0292   0.1193 -0.1744        0.2234        0.3984

## Cross-Method Summary

This last cell compares only the methods that have already been run above. It rebuilds the overlap matrix and one consensus table from the in-memory method ranks produced in this notebook.

The table is ordered by penalized average rank. If an ETF is missing from one method, that missing rank is filled with that method's `max_rank + 1`, so names that are consistently ranked well across methods rise to the top while one-off picks are penalized.

In [23]:
if not selection_results:
    raise ValueError("Run at least one selection-method cell before the summary cell.")

selection_map = {
    method_name: payload["selected"]
    for method_name, payload in selection_results.items()
}
membership = build_membership_frame(selection_map)
overlap = build_overlap_matrix(selection_map)

method_summary_rows = []
for method_name, payload in selection_results.items():
    stats = payload["stats"]
    method_summary_rows.append(
        {
            "method": method_name,
            "avg_ann_return": float(stats["ann_return"].mean()),
            "avg_ann_vol": float(stats["ann_vol"].mean()),
            "avg_sharpe": float(stats["sharpe"].mean()),
            "avg_abs_corr": float(stats["avg_abs_corr"].mean()),
        }
    )

method_summary = pd.DataFrame(method_summary_rows).sort_values(
    ["avg_sharpe", "avg_abs_corr"],
    ascending=[False, True],
)
rank_columns = [column for column in membership.columns if column.endswith("_rank")]
consensus_columns = [
    "ticker",
    "selection_count",
    *rank_columns,
]

print("Consensus table:")
display(membership.head(TOP_N)[consensus_columns].round(4))
print("Method-level summary:")
display(method_summary.round(4))

fig, axes = plt.subplots(1, 2, figsize=(16, 6), constrained_layout=True)
image = axes[0].imshow(overlap.values.astype(float), cmap="Blues")
axes[0].set_xticks(range(len(overlap.columns)), overlap.columns, rotation=30)
axes[0].set_yticks(range(len(overlap.index)), overlap.index)
axes[0].set_title(f"Top-{TOP_N} selection overlap")
for row_index in range(len(overlap.index)):
    for column_index in range(len(overlap.columns)):
        axes[0].text(
            column_index,
            row_index,
            int(overlap.iloc[row_index, column_index]),
            ha="center",
            va="center",
        )
fig.colorbar(image, ax=axes[0], fraction=0.046)

bar_colors = plt.cm.tab10(np.linspace(0, 1, len(method_summary)))
axes[1].bar(
    method_summary["method"],
    method_summary["avg_abs_corr"],
    color=bar_colors,
)
axes[1].set_title("Average absolute correlation")
axes[1].set_ylabel("Lower is better")
axes[1].grid(axis="y", alpha=0.3)

display(fig)
plt.close(fig)

Consensus table:

   ticker  selection_count  greedy_rank  kmedoids_rank  maxdiv_rank  average_rank
0     VOO                3          1.0            1.0          1.0        1.0000
1     VEA                3          2.0            2.0          2.0        2.0000
2     VWO                3          3.0            3.0          3.0        3.0000
3     TMV                3          4.0           12.0          4.0        6.6667
4     DBA                3          6.0           19.0         10.0       11.6667
5     ITB                3         21.0           13.0          6.0       13.3333
6    GLDM                2          7.0            NaN          5.0       14.3333
7     XLV                3         14.0           16.0         13.0       14.3333
8     XLU                3          8.0           29.0          8.0       15.0000
9     BNO                2          5.0            NaN         14.0       16.6667
10    XLP                3         23.0           15.0         12.0       16.6667
11   AMLP                2         11.0           17.0          NaN       19.6667
12    DXJ                3         15.0           21.0         24.0       20.0000
13   BIZD                2         12.0           18.0          NaN       20.3333
14   JETS                3         20.0           27.0         17.0       21.3333
15   VONV                1          NaN            4.0          NaN       22.0000
16    MDY                1          NaN            5.0          NaN       22.3333
17    VDE                1          NaN            6.0          NaN       22.6667
18    EWS                3         24.0           22.0         22.0       22.6667
19   FTGC                1          NaN            NaN          7.0       23.0000
20    UCO                1          NaN            7.0          NaN       23.0000
21   URNM                2          9.0            NaN         29.0       23.0000
22    SLV                1          NaN            8.0          NaN       23.3333
23    TBF                1          NaN            NaN          9.0       23.6667
24    XLF                1          NaN            9.0          NaN       23.6667
25    IYR                1          NaN           10.0          NaN       24.0000
26    KRE                1         10.0            NaN          NaN       24.0000
27    ILF                2         16.0           25.0          NaN       24.0000
28   AAAU                1          NaN            NaN         11.0       24.3333
29   GUNR                1          NaN           11.0          NaN       24.3333

Method-level summary:

     method  avg_ann_return  avg_ann_vol  avg_sharpe  avg_abs_corr
2    maxdiv          0.1140       0.2165      0.2946        0.3040
0    greedy          0.1157       0.2410      0.2706        0.3808
1  kmedoids          0.1166       0.2412      0.2635        0.4126